# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddForm(object):
    def setupUi(self, AddForm):
        AddForm.setObjectName("AddForm")
        AddForm.resize(400, 300)
        self.okButton = QtWidgets.QPushButton(AddForm)
        self.okButton.setGeometry(QtCore.QRect(90, 260, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(AddForm)
        self.cancelButton.setGeometry(QtCore.QRect(230, 260, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(AddForm)
        self.label.setGeometry(QtCore.QRect(140, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.typeEdit = QtWidgets.QLineEdit(AddForm)
        self.typeEdit.setGeometry(QtCore.QRect(180, 70, 113, 20))
        self.typeEdit.setObjectName("typeEdit")
        self.placeEdit = QtWidgets.QLineEdit(AddForm)
        self.placeEdit.setGeometry(QtCore.QRect(180, 130, 113, 20))
        self.placeEdit.setObjectName("placeEdit")
        self.massEdit = QtWidgets.QLineEdit(AddForm)
        self.massEdit.setGeometry(QtCore.QRect(180, 190, 113, 20))
        self.massEdit.setObjectName("massEdit")
        self.label_2 = QtWidgets.QLabel(AddForm)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 81, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddForm)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 71, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddForm)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 71, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(AddForm)
        QtCore.QMetaObject.connectSlotsByName(AddForm)

    def retranslateUi(self, AddForm):
        _translate = QtCore.QCoreApplication.translate
        AddForm.setWindowTitle(_translate("AddForm", "Форма добавления"))
        self.okButton.setText(_translate("AddForm", "OK"))
        self.cancelButton.setText(_translate("AddForm", "Отмена"))
        self.label.setText(_translate("AddForm", "Введите данные"))
        self.label_2.setText(_translate("AddForm", "Тип урана:"))
        self.label_3.setText(_translate("AddForm", "Точка сбора:"))
        self.label_4.setText(_translate("AddForm", "Масса (кг):"))
