# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddForm(object):
    def setupUi(self, AddForm):
        AddForm.setObjectName("AddForm")
        AddForm.resize(400, 450)
        self.okButton = QtWidgets.QPushButton(AddForm)
        self.okButton.setGeometry(QtCore.QRect(90, 390, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(AddForm)
        self.cancelButton.setGeometry(QtCore.QRect(230, 390, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(AddForm)
        self.label.setGeometry(QtCore.QRect(140, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.typeEdit = QtWidgets.QLineEdit(AddForm)
        self.typeEdit.setGeometry(QtCore.QRect(180, 140, 113, 20))
        self.typeEdit.setObjectName("typeEdit")
        self.placeEdit = QtWidgets.QLineEdit(AddForm)
        self.placeEdit.setGeometry(QtCore.QRect(180, 200, 113, 20))
        self.placeEdit.setObjectName("placeEdit")
        self.massEdit = QtWidgets.QLineEdit(AddForm)
        self.massEdit.setGeometry(QtCore.QRect(180, 260, 113, 20))
        self.massEdit.setObjectName("massEdit")
        self.label_2 = QtWidgets.QLabel(AddForm)
        self.label_2.setGeometry(QtCore.QRect(90, 140, 81, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddForm)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 71, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddForm)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 91, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.umassEdit = QtWidgets.QLineEdit(AddForm)
        self.umassEdit.setGeometry(QtCore.QRect(180, 320, 113, 20))
        self.umassEdit.setObjectName("umassEdit")
        self.label_5 = QtWidgets.QLabel(AddForm)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 141, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddForm)
        self.label_6.setGeometry(QtCore.QRect(90, 80, 81, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.dateEdit = QtWidgets.QLineEdit(AddForm)
        self.dateEdit.setGeometry(QtCore.QRect(180, 80, 113, 20))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(AddForm)
        QtCore.QMetaObject.connectSlotsByName(AddForm)

    def retranslateUi(self, AddForm):
        _translate = QtCore.QCoreApplication.translate
        AddForm.setWindowTitle(_translate("AddForm", "Форма добавления"))
        self.okButton.setText(_translate("AddForm", "OK"))
        self.cancelButton.setText(_translate("AddForm", "Отмена"))
        self.label.setText(_translate("AddForm", "Введите данные"))
        self.label_2.setText(_translate("AddForm", "Тип урана:"))
        self.label_3.setText(_translate("AddForm", "Точка сбора:"))
        self.label_4.setText(_translate("AddForm", "Масса руды (кг):"))
        self.label_5.setText(_translate("AddForm", "Масса чистого урана (кг):"))
        self.label_6.setText(_translate("AddForm", "Дата добычи:"))
