# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DelForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DelForm(object):
    def setupUi(self, DelForm):
        DelForm.setObjectName("DelForm")
        DelForm.resize(400, 300)
        self.label = QtWidgets.QLabel(DelForm)
        self.label.setGeometry(QtCore.QRect(120, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DelForm)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 201, 61))
        self.label_2.setObjectName("label_2")
        self.lineNum = QtWidgets.QLineEdit(DelForm)
        self.lineNum.setGeometry(QtCore.QRect(140, 130, 113, 20))
        self.lineNum.setObjectName("lineNum")
        self.delButton = QtWidgets.QPushButton(DelForm)
        self.delButton.setGeometry(QtCore.QRect(90, 180, 75, 23))
        self.delButton.setObjectName("delButton")
        self.cancelButton = QtWidgets.QPushButton(DelForm)
        self.cancelButton.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(DelForm)
        QtCore.QMetaObject.connectSlotsByName(DelForm)

    def retranslateUi(self, DelForm):
        _translate = QtCore.QCoreApplication.translate
        DelForm.setWindowTitle(_translate("DelForm", "Удаление записи"))
        self.label.setText(_translate("DelForm", "Удаление записи"))
        self.label_2.setText(_translate("DelForm", "Введите номер записи для удаления:"))
        self.delButton.setText(_translate("DelForm", "Удалить"))
        self.cancelButton.setText(_translate("DelForm", "Отмена"))
