# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphForm(object):
    def setupUi(self, GraphForm):
        GraphForm.setObjectName("GraphForm")
        GraphForm.resize(400, 350)
        self.label = QtWidgets.QLabel(GraphForm)
        self.label.setGeometry(QtCore.QRect(100, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.graph1Button = QtWidgets.QPushButton(GraphForm)
        self.graph1Button.setGeometry(QtCore.QRect(120, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graph1Button.setFont(font)
        self.graph1Button.setObjectName("graph1Button")
        self.graph2Button = QtWidgets.QPushButton(GraphForm)
        self.graph2Button.setGeometry(QtCore.QRect(120, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graph2Button.setFont(font)
        self.graph2Button.setObjectName("graph2Button")
        self.graph3Button = QtWidgets.QPushButton(GraphForm)
        self.graph3Button.setGeometry(QtCore.QRect(120, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graph3Button.setFont(font)
        self.graph3Button.setObjectName("graph3Button")
        self.cancelButton = QtWidgets.QPushButton(GraphForm)
        self.cancelButton.setGeometry(QtCore.QRect(120, 280, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(GraphForm)
        QtCore.QMetaObject.connectSlotsByName(GraphForm)

    def retranslateUi(self, GraphForm):
        _translate = QtCore.QCoreApplication.translate
        GraphForm.setWindowTitle(_translate("GraphForm", "Выбор графика"))
        self.label.setText(_translate("GraphForm", "Выберите график"))
        self.graph1Button.setText(_translate("GraphForm", "График 1"))
        self.graph2Button.setText(_translate("GraphForm", "График 2"))
        self.graph3Button.setText(_translate("GraphForm", "График 3"))
        self.cancelButton.setText(_translate("GraphForm", "Назад"))
