# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Redaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Redaction(object):
    def setupUi(self, Redaction):
        Redaction.setObjectName("Redaction")
        Redaction.resize(305, 340)
        self.label = QtWidgets.QLabel(Redaction)
        self.label.setGeometry(QtCore.QRect(60, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addButton = QtWidgets.QPushButton(Redaction)
        self.addButton.setGeometry(QtCore.QRect(100, 90, 110, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.changeButton = QtWidgets.QPushButton(Redaction)
        self.changeButton.setGeometry(QtCore.QRect(100, 140, 110, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.changeButton.setFont(font)
        self.changeButton.setObjectName("changeButton")
        self.delButton = QtWidgets.QPushButton(Redaction)
        self.delButton.setGeometry(QtCore.QRect(100, 190, 110, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delButton.setFont(font)
        self.delButton.setObjectName("delButton")
        self.cancelButton = QtWidgets.QPushButton(Redaction)
        self.cancelButton.setGeometry(QtCore.QRect(100, 270, 110, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Redaction)
        QtCore.QMetaObject.connectSlotsByName(Redaction)

    def retranslateUi(self, Redaction):
        _translate = QtCore.QCoreApplication.translate
        Redaction.setWindowTitle(_translate("Redaction", "Выбор действия"))
        self.label.setText(_translate("Redaction", "Действия с записями:"))
        self.addButton.setText(_translate("Redaction", "Добавить"))
        self.changeButton.setText(_translate("Redaction", "Изменить"))
        self.delButton.setText(_translate("Redaction", "Удалить"))
        self.cancelButton.setText(_translate("Redaction", "Назад"))
