# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelNote(object):
    def setupUi(self, SelNote):
        SelNote.setObjectName("SelNote")
        SelNote.resize(400, 300)
        self.label = QtWidgets.QLabel(SelNote)
        self.label.setGeometry(QtCore.QRect(120, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SelNote)
        self.label_2.setGeometry(QtCore.QRect(100, 70, 201, 61))
        self.label_2.setObjectName("label_2")
        self.lineNum = QtWidgets.QLineEdit(SelNote)
        self.lineNum.setGeometry(QtCore.QRect(140, 130, 113, 20))
        self.lineNum.setObjectName("lineNum")
        self.okButton = QtWidgets.QPushButton(SelNote)
        self.okButton.setGeometry(QtCore.QRect(90, 180, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(SelNote)
        self.cancelButton.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(SelNote)
        QtCore.QMetaObject.connectSlotsByName(SelNote)

    def retranslateUi(self, SelNote):
        _translate = QtCore.QCoreApplication.translate
        SelNote.setWindowTitle(_translate("SelNote", "Изменение записи"))
        self.label.setText(_translate("SelNote", "Выберите запись"))
        self.label_2.setText(_translate("SelNote", "Введите номер записи для изменения:"))
        self.okButton.setText(_translate("SelNote", "ОК"))
        self.cancelButton.setText(_translate("SelNote", "Отмена"))
